# Generated by Django 5.1.6 on 2025-02-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('frequency', models.IntegerField(help_text='Buses per hour')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('passenger_flow', models.IntegerField(help_text='Average number of passengers per day')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position in route')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_optimization_app.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_optimization_app.stop')),
            ],
            options={
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'stop', 'order')},
            },
        ),
    ]
